# Generated by Django 4.1.1 on 2024-03-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_enquiry_requests_remove_request_payment_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_offered', models.TextField(blank=True, null=True)),
                ('payment_term_offered', models.TextField(blank=True, null=True)),
                ('validity_offered', models.TextField(blank=True, null=True)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_client', to='app.request')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.supplier')),
            ],
        ),
    ]
