# Generated by Django 4.1.1 on 2024-05-31 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_email_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="email",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="app.email",
            ),
        ),
    ]
