# Generated by Django 4.1.1 on 2024-07-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_alter_offer_client_validity_offered"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enquiry",
                to="app.enquiry",
            ),
        ),
        migrations.AddField(
            model_name="offer_client",
            name="margin",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="app.email",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request",
                to="app.request",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="manager",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.manager",
            ),
        ),
    ]
