# Generated by Django 4.1.1 on 2024-07-18 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_offer_client_incoterms"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("personal_phone", models.TextField(blank=True, null=True)),
                ("job_title", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="client",
            name="person",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="email",
        ),
        migrations.AddField(
            model_name="client",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offer_client",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="contacts",
            field=models.ManyToManyField(
                related_name="clients", to="app.companycontact"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="contacts",
            field=models.ManyToManyField(
                related_name="suppliers", to="app.companycontact"
            ),
        ),
    ]
