# Generated by Django 4.1.1 on 2024-04-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_offer_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
