# Generated by Django 5.0.6 on 2024-05-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
