# Generated by Django 5.0.6 on 2024-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_userprofile_access_token_userprofile_expiry_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expiry_token',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
