# Generated by Django 5.0.6 on 2024-05-16 14:58

import django.core.files.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_manager_access_token_manager_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='customer_feedback',
        ),
        migrations.RemoveField(
            model_name='request',
            name='offer_selected',
        ),
        migrations.RemoveField(
            model_name='request',
            name='payment_term_offered',
        ),
        migrations.RemoveField(
            model_name='request',
            name='price_offered',
        ),
        migrations.RemoveField(
            model_name='request',
            name='validity_offered',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='manager',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('DRAFT', 'Draft')], default='Draft', max_length=10)),
                ('response_received', models.BooleanField(default=False)),
                ('response_details', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manager')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.request')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/email_attachments'), upload_to='email_attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='app.request')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.email')),
            ],
        ),
    ]
