# Generated by Django 4.1.1 on 2024-06-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_attachment_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.division",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="products",
            field=models.ManyToManyField(related_name="suppliers", to="app.product"),
        ),
    ]
