# Generated by Django 4.1.1 on 2024-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_supplier_division_supplier_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="discharge_port",
        ),
        migrations.AddField(
            model_name="request",
            name="delivery_schedule",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="quantity_unit",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="target_price",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
