# Generated by Django 4.1.1 on 2024-07-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_remove_request_discharge_port_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer_client",
            name="validity_offered",
            field=models.DateField(blank=True, null=True),
        ),
    ]
