# Generated by Django 4.1.1 on 2024-07-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_attachment_enquiry_offer_client_margin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.manager",
            ),
        ),
    ]
