# Generated by Django 4.1.1 on 2024-07-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_alter_enquiry_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="app.enquiry",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="app.request",
            ),
        ),
    ]
