# Generated by Django 4.1.1 on 2024-07-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_attachment_enquiry_alter_attachment_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="cc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="recipient",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="subject",
            field=models.TextField(blank=True, null=True),
        ),
    ]
