# Generated by Django 4.1.1 on 2024-07-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_email_cc_alter_email_message_alter_email_recipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer_client",
            name="incoterms",
            field=models.TextField(blank=True, null=True),
        ),
    ]
